server:
  port: 7070

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hr
    username: root
    password: test

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: ture
        show_sql: true

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      sql: DEBUG